repos:
- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
    - id: black
- repo: https://github.com/pycqa/pylint
  rev: v3.3.1
  hooks:
    - id: pylint
- repo: local
  hooks:
    - id: run-pytests
      name: Run Pytest
      entry: python -m pytest tests
      language: system
      types: [python]
      pass_filenames: false