name: sentinel3-sral-demo
channels:
  - defaults
  - conda-forge
  - eumetsat
dependencies:
  - python=3.12
  - conda-forge::pytest=8.3
  - conda-forge::black=24.8.0
  - conda-forge::pylint=3.3.1
  - conda-forge::pre-commit=3.8.0
  # External
  - eumetsat::eumdac
