name: sentinel3-sral-demo
channels:
  - defaults
  - conda-forge
  - eumetsat
dependencies:
  - python=3.12
  - conda-forge::pytest=8.3
  - conda-forge::pytest-mock=3.14.0
  - conda-forge::pytest-cov=5.0.0
  - conda-forge::black=24.8.0
  - conda-forge::netcdf4=1.7.1
  - conda-forge::pylint=3.3.1
  - conda-forge::pre-commit=3.8.0
  - conda-forge::xarray
  - conda-forge::zarr=2.18.3
  - conda-forge::zcollection=2024.2.0
  # External
  - eumetsat::eumdac
